// Hoje aprenderemos como utilizar fun√ß√µes ass√≠ncronas no NodeJS.

// Voc√™ ser√° capaz de:
// Realizar opera√ß√µes ass√≠ncronas utilizando callbacks;
// Realizar opera√ß√µes ass√≠ncronas utilizando Promises;
// Ler e escrever arquivos localmente com Node.js;
// Escrever seus pr√≥prios scripts que criam e consomem Promises;
// Reescrever c√≥digo que usa callbacks para que use Promises.

// Exemplo de callback usando fs do NodeJS
const fs = require('fs');

fs.readFile('./arquivo.txt', (err, content) => {
  if (err) {
    console.error(`Erro ao ler o arquivo: ${err.message}`);
    return;
  }

  console.log(`Arquivo lido com sucesso. Conte√∫do: ${content.toString('utf8')}`);
});

// Esse formato de callback que recebe dois par√¢metros, erro e resultado, n√£o foi utilizado por acaso. Callbacks desse tipo s√£o chamadas de node-style callbacks e s√£o, por conven√ß√£o, a melhor maneira de se estruturar uma callback. Toda API de m√≥dulos nativos do Node.js utiliza esse mesmo formato de callbacks . Guarde essa informa√ß√£o, pois ela vai ser importante mais tarde. üòâ

// Fun√ß√£o de divis√£o simples usando a cria√ß√£o de new Promise.
function dividirNumeros(num1, num2) {
  const promise = new Promise((resolve, reject) => {
    if (num2 == 0) reject(new Error("N√£o pode ser feito uma divis√£o por zero"));

    const resultado = num1 / num2;
    resolve(resultado)
  });

  return promise;
}

dividirNumeros(2, 1)
  .then(result => console.log(`sucesso: ${result}`))
  .catch(err => console.log(`erro: ${err.message}`));

// Agora, de forma s√≠ncrona:
function dividirNumeros(num1, num2) {
  if (num2 == 0) throw new Error("N√£o pode ser feito uma divis√£o por zero");

  return num1 / num2;
}

try {
  const resultado = dividirNumeros(2, 1);
  console.log(`resultado: ${resultado}`);
} catch (e) {
  console.log(e.message);
}
